# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('pginkhrar', 'PG In Khrar'), ('pgaroundkhrar', 'PG Around Khrar')], default='pginkhrar', max_length=15)),
                ('pgname', models.CharField(max_length=150)),
                ('pgtype', models.CharField(max_length=150)),
                ('pglocation', models.CharField(max_length=256)),
                ('pgdescription', models.CharField(max_length=500)),
                ('pgprice', models.IntegerField()),
                ('pgcondition', models.CharField(max_length=150)),
                ('pgmeals', models.CharField(max_length=256)),
                ('ownername', models.CharField(max_length=50)),
                ('pgmobile', models.BigIntegerField()),
                ('ammenities1', models.CharField(max_length=100)),
                ('ammenities2', models.CharField(max_length=100)),
                ('ammenities3', models.CharField(max_length=100)),
                ('ammenities4', models.CharField(max_length=100)),
                ('ammenities5', models.CharField(max_length=100)),
                ('ammenities6', models.CharField(blank=True, max_length=100, null=True)),
                ('ammenities7', models.CharField(blank=True, max_length=100, null=True)),
                ('ammenities8', models.CharField(blank=True, max_length=100, null=True)),
                ('ammenities9', models.CharField(blank=True, max_length=100, null=True)),
                ('ammenities10', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('pgimage1', models.ImageField(upload_to='images')),
                ('pgimage2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pgimage3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
